name: Regression Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  
  schedule:
    - cron: '0 2 * * *'
      
jobs:
  run-tests:

    strategy:

      matrix:

        browser:
          - chrome
          - firefox
          - edge

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create Database
        run: python setup_db.py

      - name: Show Trigger
        run: echo "Triggered by ${{ github.event_name }}"

      - name: Run Smoke Tests

        if: github.event_name != 'schedule'

        run: pytest -m smoke --headless --browser ${{ matrix.browser }}

      - name: Run Regression Tests

        if: github.event_name == 'schedule'

        run: pytest -m regression --headless --browser ${{ matrix.browser }}

      - name: Upload Screenshots

        if: always()

        uses: actions/upload-artifact@v4

        with:
          name: screenshots-${{ matrix.browser }}
          path: screenshots/

      - name: Show Browser
        run: echo "Running on ${{ matrix.browser }}"

      - name: Show Browser
        run: echo "${{ matrix.browser }}"